version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: servisin_user
      POSTGRES_PASSWORD: servisin_password
      POSTGRES_DB: servisin_dev
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env   
    environment:
      DATABASE_URL: postgres://servisin_user:servisin_password@db:5432/servisin_dev?sslmode=disable
      PORT: 8080
    depends_on:
      - db
    ports:
      - "8000:8080"

volumes:
  db_data:
