name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "./*"
          target: /home/servisin-be
          script: |
            cd /home/servisin-be
            git pull origin main
            docker compose down
            docker compose up -d --build


# name: CI/CD Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: '1.23'

#       - name: Build Go binary
#         run: |
#           go mod download
#           go build -o myapp

#       # - name: Debug workspace
#       #   run: |
#       #     echo "Workspace content:"
#       #     ls -lah
#       #     echo "Find recursively:"
#       #     find . -maxdepth 2 -type f

#       - name: Copy files to server
#         uses: appleboy/scp-action@v0.1.6
#         with:
#           host: ${{ secrets.DEPLOY_HOST }}
#           username: ${{ secrets.DEPLOY_USER }}
#           port: ${{ secrets.DEPLOY_PORT }}
#           key: ${{ secrets.DEPLOY_SSH_KEY }}
#           source: "./*"
#           target: /home/servisin-be

#       - name: SSH & Restart Docker
#         uses: appleboy/ssh-action@v0.1.6
#         with:
#           host: ${{ secrets.DEPLOY_HOST }}
#           username: ${{ secrets.DEPLOY_USER }}
#           port: ${{ secrets.DEPLOY_PORT }}
#           key: ${{ secrets.DEPLOY_SSH_KEY }}
#           script: |
#             cd /home/servisin-be
#             docker compose pull
#             docker compose up -d --build
